### ISSUE TITLE
adobe-reader-dc@22.001.20169: hash check failed

### ISSUE THREAD

**Issue by fifteenblade** [mbl-35/scoop-srsrns#1]
scoop install adobe-reader-dc
WARN  Purging previous failed installation of adobe-reader-dc.
ERROR 'adobe-reader-dc' isn't installed correctly.
Removing older version (22.001.20169).
'adobe-reader-dc' was uninstalled.
Installing 'adobe-reader-dc' (22.001.20169) [64bit] from mbl-35_scoop-srsrns bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c74187|OK  |    21MiB/s|C:/Users/Administrator/scoop/cache/adobe-reader-dc#22.001.20169#http_ardownload.adobe.com_pub_adobe_reader_win_AcrobatDC_2200120169_AcroRdrDC2200120169_en_US.exe_cosi.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of AcroRdrDC2200120169_en_US.exe ... ERROR Hash check failed!
App:         mbl-35_scoop-srsrns/adobe-reader-dc
URL:         http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2200120169/AcroRdrDC2200120169_en_US.exe#/cosi.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    3f0fcc53dff0eaf3b638ace538b618a9369f131c68e599beaa614b45c895ad13
Actual:      73aed750bbe18d0c010dde9957c57497d2b67f9d3107fcd0e4314220e284f993

**Comment by mbl-35** [comment]
Thanks @fifteenblade 
Resolved by ugrading the adobe current version to 22.002.20191 ;)
